In [1]:
import numpy as np
from production.Tools import Vector, Matrix

In [2]:

def is_dependent(*args):
    if not args:
        raise ValueError("No input provided.")

    if len(args) == 1:
        # a  matrix
        matrix = args[0]
        matrix = Matrix(matrix).data if not isinstance(matrix, Matrix) else matrix

    else:
        vectors = [Vector(v).data if not isinstance(v, Vector) else v for v in args]
        matrix = Matrix(np.array(vectors)).data

    rank = np.linalg.matrix_rank(matrix)
    vector_num = matrix.data.shape[1]  # col num = vector num
    print("Matrix:", matrix)
    print("Rank:", rank)
    print("Shape:", matrix.shape)
    print("Dims:", matrix.ndim)
    print("Cols:", vector_num)
    return rank < vector_num

In [ ]:



a = np.array([1, 2])
b = np.array([4, 8])
c = np.array([a, b]).T



is_dependent(c)  # test for matrix NDARRAY
is_dependent([[1, 4], [2, 8]])  # test for matrix NO NDARRAY


is_dependent([1], [2], [3])  # test for vector NDARRAYS
is_dependent([[1, 4], [2, 8]])  # test for matrix NO NDARRAY

In [ ]:
m = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
m = np.array(m)
m_rank = np.linalg.matrix_rank(m)

matrix = Matrix(m)
matrix_rank = np.linalg.matrix_rank(matrix.data)

m_rank, matrix.rank()
is_dependent(m)

In [ ]:
v1 = [1, 0, 0]
v2 = [0, 1, 0]
v3 = [0, 0, 1]

is_dependent(v1, v2, v3)

In [4]:
import numpy as np
from production.Tools import Vector, Matrix
from typing import Optional, Literal

In [ ]:
def is_linear_transformation(
    transformation_matrix: Matrix,
    v1: Optional[Vector] = None,
    v2: Optional[Vector] = None,
    c: Optional[float] = None,
):
    # generate 2 random 2D vectors
    if not (v1 and v2):
        v1, v2 = np.random.random(size=(2, 2))
        v1, v2 = Vector(v1), Vector(v2)
    else:
        if not isinstance(v1, Vector):
            v1 = Vector(v1)
        elif not isinstance(v2, Vector):
            v2 = Vector(v2)
    # random scalar
    c = np.random.rand()

    A = (
        Matrix(transformation_matrix)
        if not isinstance(transformation_matrix, Matrix)
        else transformation_matrix
    )

    additivity = np.allclose(A @ (v1 + v2), A @ v1 + A @ v2)
    homogeneity = np.allclose(A @ (c * v1), c * (A @ v1))

    print(additivity, homogeneity)
    return additivity and homogeneity


is_linear_transformation([[-1, 0], [0, 1]])

In [ ]:
def apply_rotation(
    base_vector, angle: float | int, direction: Literal["right", "left"] = "right"
):
    num_coordinates = base_vector.shape[0]
    num_vectors = base_vector.shape[1]

def rotate_30(direction: Literal["right", "left"] = "right"):
    pass

def rotate_45(direction: Literal["right", "left"] = "right"):
    pass

def rotate_2D_90(self, direction: Literal["right", "left"] = "right"):
    if direction == "right":
        A = Matrix([[0, -1], [1, 0]])
    elif direction == "left":
        A = Matrix([[-1, 0], [0, 1]])

    return A @ self
    
def rotate_180(direction: Literal["right", "left"] = "right"):
    pass

def rotate_270(direction: Literal["right", "left"] = "right"):
    pass

def rotate_360(direction: Literal["right", "left"] = "right"):
    pass

In [ ]:
Matrix([[1, 2], [4, 5]]).rotate_2D_90()

---

In [1]:
import numpy as np
from IPython.display import display, Math
from typing import Optional


In [10]:
class Vector(np.ndarray):
    """
    A class representing a mathematical vector that inherits from numpy.ndarray.

    This ensures that the Vector behaves like a numpy array and supports all
    operations such as addition, multiplication, etc.

    Attributes:
        data (numpy.ndarray): The data of the vector as a 1D numpy array.
    """

    def __new__(cls, data):
        
        try:
            import IPython
            get_ipython()  # type: ignore
            cls.ipython_env = True
        except:
            cls.ipython_env = False

        # Convert input data into a numpy array and ensure it's a 1D vector
        obj = np.asarray(data).squeeze()  # Remove any singleton dimensions

        # If it's a 2D column vector, flatten it to 1D
        if obj.ndim == 2 and obj.shape[1] == 1:
            obj = obj.flatten()

        # If it's not a 1D array after squeezing, raise an error
        if obj.ndim != 1:
            raise ValueError("A vector must be a 1D array.")

        # Return a new object with the desired class (Vector)
        return obj.view(cls)

    def __repr__(self):
        # If there are more than 5 elements, format it with first 2, ellipsis, and last 2
        if self.ipython_env:

            if len(self) > 5:
                latex_repr = (
                    r"Vector\left(\begin{bmatrix} "
                    + " \\\\ ".join(map(str, self[:2]))
                    + r" \\\\ \vdots \\\\ "
                    + " \\\\ ".join(map(str, self[-2:]))
                    + r" \end{bmatrix}\right)"
                )
            else:
                latex_repr = (
                    r"Vector\left(\begin{bmatrix} "
                    + " \\\\ ".join(map(str, self))
                    + r" \end{bmatrix}\right)"
                )

            display(Math(latex_repr))
            return ""
        else:
            return f"Vector({', '.join(map(str, self))})"

    def add_vector(self, vector):
        base_vector = self

        # Ensure 'vector' is a Vector instance
        if not isinstance(vector, Vector):
            vector = Vector(vector)

        # Check if shapes are compatible
        if base_vector.shape != vector.shape:
            raise ValueError(f"Shapes must be equal, got {base_vector.shape} + {vector.shape}")

        # Perform addition and return a new Vector instance
        return Vector(base_vector + vector)

    def subtract_vector(self, vector):
        base_vector = self
        
        # Ensure 'vector' is a Vector instance
        if not isinstance(vector, Vector):
            vector = Vector(vector)

        # Check if shapes are compatible
        if base_vector.shape != vector.shape:
            raise ValueError(f"Shapes must be equal, got {base_vector.shape} - {vector.shape}")

        # Perform subtraction and return a new Vector instance
        return Vector(base_vector - vector)

    def scalar_multiply(self, scalar: int | float):
        base_vector = self
        
        if not isinstance(scalar, (int, float)):
            raise TypeError(f"`scalar` must be of type `int|float`, got {type(scalar)}")

        return Vector(base_vector * scalar)

    def is_dependent(self, *vectors) -> bool:
        base_vector = self
        if not vectors:
            raise ValueError("No input provided.")

        vectors = [base_vector] + [Vector(v) if not isinstance(v, Vector) else v for v in vectors]
        matrix = np.column_stack(vectors)

        rank = np.linalg.matrix_rank(matrix)
        vector_num = matrix.shape[1]  # col num = vector num
        print("Matrix:", matrix)
        print("Rank:", rank)
        print("Shape:", matrix.shape)
        print("Dims:", matrix.ndim)
        print("Cols:", vector_num)
        return bool(rank < vector_num)

    def find_linear_combination(self, *vectors) -> Optional[np.ndarray]:
        base_vector = self
        vectors = [Vector(v) if not isinstance(v, Vector) else v for v in vectors]
        matrix = np.column_stack(vectors)
        try:
            coefficients, residuals, rank, s = np.linalg.lstsq(matrix, base_vector, rcond=None)
          # If the residuals are sufficiently small, return the coefficients
            if np.allclose(np.dot(matrix, coefficients), base_vector):  # Check if A*c is close to b
                return coefficients
            else:
                return None  # No valid linear combination
        except np.linalg.LinAlgError as e:
            print(f"An error occurred: {e}")
            return None  # In case of any numerical errors

    def find_span(self, *basis_vectors, include_self: bool = False) -> dict:
        base_vector = self
        if not basis_vectors:  
            vectors = [base_vector]
        else:  
            if include_self: 
                vectors = [base_vector] + [Vector(v) if not isinstance(v, Vector) else v for v in basis_vectors]
            else:
                vectors = [Vector(v) if not isinstance(v, Vector) else v for v in basis_vectors]
                
        matrix = np.column_stack(vectors)
        output = {
            "rank": 0,  # Dimension of the span (rank)
            "full_span": False,  # Whether the span fills the entire space
            "zero_span": False,  # Whether the span is trivial (zero vector only)
        }
        print(matrix)
        rank = np.linalg.matrix_rank(matrix)
        n_vectors = matrix.shape[1] # Number of vectors is equal to number of columns
        output["rank"] = int(rank)
        print(rank, n_vectors)
        if rank == 0:
            output["zero_span"] = True
        elif rank == n_vectors:
            output["full_span"] = True
        
        return output
   
    def is_basis(self, *vectors) -> bool:
        return not self.is_dependent(*vectors)
             
   
class Matrix(np.ndarray):
    
    """
    A class representing a mathematical matrix that inherits from numpy.ndarray.

    This ensures that the Matrix behaves like a numpy array and supports all
    operations such as addition, multiplication, etc.

    Attributes:
        data (numpy.ndarray): The data of the matrix as a 2D numpy array.
    """

    def __new__(cls, data):
        # Convert input data into a numpy array and ensure it's 2D
        obj = np.asarray(data)
        if obj.ndim not in [1, 2]:
            raise ValueError("A matrix must be either a 1D or 2D array.")

        # Handle 1D array by reshaping it into a 1xN matrix
        if obj.ndim == 1:
            obj = obj.reshape(1, -1)

        # Handle single-column matrix to row vector conversion
        if obj.ndim == 2 and obj.shape[1] == 1:
            obj = obj.T

        return obj.view(cls)

    def __repr__(self):
        return super().__repr__()

    def rank(self):
        return np.linalg.matrix_rank(self)

In [3]:
_a = [1, 2, 3]
_b = [11, 22, 33]
_c = [111, 222, 333]
_d = [111, 222, 333, 444]
_e = [1, 5, 19]
a, b, c, d, e = Vector(_a), Vector(_b), Vector(_c), Vector(_d), Vector(_e)

In [4]:
 # Create an instance of Vector A
A = Vector([1, 2, 3])

# Simple tests for .find_span method
span_result_1 = A.find_span([1, 0, 0], [0, 1, 0], [0, 0, 1])
span_result_2 = A.find_span([1, 2, 3], [2, 4, 6])
span_result_3 = A.find_span([1, 2, 3], [4, 5, 6])
span_result_4 = A.find_span( [4, 5, 6], include_self=True)

print("Span Result 1:", span_result_1)
print("Span Result 2:", span_result_2)
print("Span Result 3:", span_result_3)
print("Span Result 4:", span_result_4)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
3 3
[[1 2]
 [2 4]
 [3 6]]
1 2
[[1 4]
 [2 5]
 [3 6]]
2 2
[[1 4]
 [2 5]
 [3 6]]
2 2
Span Result 1: {'rank': 3, 'full_span': True, 'zero_span': False}
Span Result 2: {'rank': 1, 'full_span': False, 'zero_span': False}
Span Result 3: {'rank': 2, 'full_span': True, 'zero_span': False}
Span Result 4: {'rank': 2, 'full_span': True, 'zero_span': False}


In [5]:
print(a.find_linear_combination(b, c))

[0.0008841 0.0089214]


In [6]:
0.0008841  * b + 0.0089214 * c

<IPython.core.display.Math object>

In [7]:
a.add_vector(b)

<IPython.core.display.Math object>

In [8]:
a.scalar_multiply(21)

<IPython.core.display.Math object>

In [9]:
a.is_dependent(d)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [57]:
a.is_linear_combination(d)

AttributeError: 'Vector' object has no attribute 'is_linear_combination'