In [1]:
import numpy as np
from production.Tools import Vector, Matrix

In [2]:

def is_dependent(*args):
    if not args:
        raise ValueError("No input provided.")

    if len(args) == 1:
        # a  matrix
        matrix = args[0]
        matrix = Matrix(matrix).data if not isinstance(matrix, Matrix) else matrix

    else:
        vectors = [Vector(v).data if not isinstance(v, Vector) else v for v in args]
        matrix = Matrix(np.array(vectors)).data

    rank = np.linalg.matrix_rank(matrix)
    vector_num = matrix.data.shape[1]  # col num = vector num
    print("Matrix:", matrix)
    print("Rank:", rank)
    print("Shape:", matrix.shape)
    print("Dims:", matrix.ndim)
    print("Cols:", vector_num)
    return rank < vector_num

In [ ]:



a = np.array([1, 2])
b = np.array([4, 8])
c = np.array([a, b]).T



is_dependent(c)  # test for matrix NDARRAY
is_dependent([[1, 4], [2, 8]])  # test for matrix NO NDARRAY


is_dependent([1], [2], [3])  # test for vector NDARRAYS
is_dependent([[1, 4], [2, 8]])  # test for matrix NO NDARRAY

In [ ]:
m = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
m = np.array(m)
m_rank = np.linalg.matrix_rank(m)

matrix = Matrix(m)
matrix_rank = np.linalg.matrix_rank(matrix.data)

m_rank, matrix.rank()
is_dependent(m)

In [ ]:
v1 = [1, 0, 0]
v2 = [0, 1, 0]
v3 = [0, 0, 1]

is_dependent(v1, v2, v3)

In [4]:
import numpy as np
from production.Tools import Vector, Matrix
from typing import Optional, Literal

In [ ]:
def is_linear_transformation(
    transformation_matrix: Matrix,
    v1: Optional[Vector] = None,
    v2: Optional[Vector] = None,
    c: Optional[float] = None,
):
    # generate 2 random 2D vectors
    if not (v1 and v2):
        v1, v2 = np.random.random(size=(2, 2))
        v1, v2 = Vector(v1), Vector(v2)
    else:
        if not isinstance(v1, Vector):
            v1 = Vector(v1)
        elif not isinstance(v2, Vector):
            v2 = Vector(v2)
    # random scalar
    c = np.random.rand()

    A = (
        Matrix(transformation_matrix)
        if not isinstance(transformation_matrix, Matrix)
        else transformation_matrix
    )

    additivity = np.allclose(A @ (v1 + v2), A @ v1 + A @ v2)
    homogeneity = np.allclose(A @ (c * v1), c * (A @ v1))

    print(additivity, homogeneity)
    return additivity and homogeneity


is_linear_transformation([[-1, 0], [0, 1]])

In [ ]:
def apply_rotation(
    base_vector, angle: float | int, direction: Literal["right", "left"] = "right"
):
    num_coordinates = base_vector.shape[0]
    num_vectors = base_vector.shape[1]

def rotate_30(direction: Literal["right", "left"] = "right"):
    pass

def rotate_45(direction: Literal["right", "left"] = "right"):
    pass

def rotate_2D_90(self, direction: Literal["right", "left"] = "right"):
    if direction == "right":
        A = Matrix([[0, -1], [1, 0]])
    elif direction == "left":
        A = Matrix([[-1, 0], [0, 1]])

    return A @ self
    
def rotate_180(direction: Literal["right", "left"] = "right"):
    pass

def rotate_270(direction: Literal["right", "left"] = "right"):
    pass

def rotate_360(direction: Literal["right", "left"] = "right"):
    pass

In [ ]:
Matrix([[1, 2], [4, 5]]).rotate_2D_90()

---

In [1]:
import numpy as np
from IPython.display import display, Math
from typing import Optional


In [10]:
class Vector(np.ndarray):
    """
    A class representing a mathematical vector that inherits from numpy.ndarray.

    This ensures that the Vector behaves like a numpy array and supports all
    operations such as addition, multiplication, etc.

    Attributes:
        data (numpy.ndarray): The data of the vector as a 1D numpy array.
    """

    def __new__(cls, data):
        
        try:
            import IPython
            get_ipython()  # type: ignore
            cls.ipython_env = True
        except:
            cls.ipython_env = False

        # Convert input data into a numpy array and ensure it's a 1D vector
        obj = np.asarray(data).squeeze()  # Remove any singleton dimensions

        # If it's a 2D column vector, flatten it to 1D
        if obj.ndim == 2 and obj.shape[1] == 1:
            obj = obj.flatten()

        # If it's not a 1D array after squeezing, raise an error
        if obj.ndim != 1:
            raise ValueError("A vector must be a 1D array.")

        # Return a new object with the desired class (Vector)
        return obj.view(cls)

    def __repr__(self):
        # If there are more than 5 elements, format it with first 2, ellipsis, and last 2
        if self.ipython_env:

            if len(self) > 5:
                latex_repr = (
                    r"Vector\left(\begin{bmatrix} "
                    + " \\\\ ".join(map(str, self[:2]))
                    + r" \\\\ \vdots \\\\ "
                    + " \\\\ ".join(map(str, self[-2:]))
                    + r" \end{bmatrix}\right)"
                )
            else:
                latex_repr = (
                    r"Vector\left(\begin{bmatrix} "
                    + " \\\\ ".join(map(str, self))
                    + r" \end{bmatrix}\right)"
                )

            display(Math(latex_repr))
            return ""
        else:
            return f"Vector({', '.join(map(str, self))})"

    def add_vector(self, vector):
        base_vector = self

        # Ensure 'vector' is a Vector instance
        if not isinstance(vector, Vector):
            vector = Vector(vector)

        # Check if shapes are compatible
        if base_vector.shape != vector.shape:
            raise ValueError(f"Shapes must be equal, got {base_vector.shape} + {vector.shape}")

        # Perform addition and return a new Vector instance
        return Vector(base_vector + vector)

    def subtract_vector(self, vector):
        base_vector = self
        
        # Ensure 'vector' is a Vector instance
        if not isinstance(vector, Vector):
            vector = Vector(vector)

        # Check if shapes are compatible
        if base_vector.shape != vector.shape:
            raise ValueError(f"Shapes must be equal, got {base_vector.shape} - {vector.shape}")

        # Perform subtraction and return a new Vector instance
        return Vector(base_vector - vector)

    def scalar_multiply(self, scalar: int | float):
        base_vector = self
        
        if not isinstance(scalar, (int, float)):
            raise TypeError(f"`scalar` must be of type `int|float`, got {type(scalar)}")

        return Vector(base_vector * scalar)

    def is_dependent(self, *vectors) -> bool:
        base_vector = self
        if not vectors:
            raise ValueError("No input provided.")

        vectors = [base_vector] + [Vector(v) if not isinstance(v, Vector) else v for v in vectors]
        matrix = np.column_stack(vectors)

        rank = np.linalg.matrix_rank(matrix)
        vector_num = matrix.shape[1]  # col num = vector num
        print("Matrix:", matrix)
        print("Rank:", rank)
        print("Shape:", matrix.shape)
        print("Dims:", matrix.ndim)
        print("Cols:", vector_num)
        return bool(rank < vector_num)

    def find_linear_combination(self, *vectors) -> Optional[np.ndarray]:
        base_vector = self
        vectors = [Vector(v) if not isinstance(v, Vector) else v for v in vectors]
        matrix = np.column_stack(vectors)
        try:
            coefficients, residuals, rank, s = np.linalg.lstsq(matrix, base_vector, rcond=None)
          # If the residuals are sufficiently small, return the coefficients
            if np.allclose(np.dot(matrix, coefficients), base_vector):  # Check if A*c is close to b
                return coefficients
            else:
                return None  # No valid linear combination
        except np.linalg.LinAlgError as e:
            print(f"An error occurred: {e}")
            return None  # In case of any numerical errors

    def find_span(self, *basis_vectors, include_self: bool = False) -> dict:
        base_vector = self
        if not basis_vectors:  
            vectors = [base_vector]
        else:  
            if include_self: 
                vectors = [base_vector] + [Vector(v) if not isinstance(v, Vector) else v for v in basis_vectors]
            else:
                vectors = [Vector(v) if not isinstance(v, Vector) else v for v in basis_vectors]
                
        matrix = np.column_stack(vectors)
        output = {
            "rank": 0,  # Dimension of the span (rank)
            "full_span": False,  # Whether the span fills the entire space
            "zero_span": False,  # Whether the span is trivial (zero vector only)
        }
        print(matrix)
        rank = np.linalg.matrix_rank(matrix)
        n_vectors = matrix.shape[1] # Number of vectors is equal to number of columns
        output["rank"] = int(rank)
        print(rank, n_vectors)
        if rank == 0:
            output["zero_span"] = True
        elif rank == n_vectors:
            output["full_span"] = True
        
        return output
   
    def is_basis(self, *vectors) -> bool:
        return not self.is_dependent(*vectors)
             
   
class Matrix(np.ndarray):
    
    """
    A class representing a mathematical matrix that inherits from numpy.ndarray.

    This ensures that the Matrix behaves like a numpy array and supports all
    operations such as addition, multiplication, etc.

    Attributes:
        data (numpy.ndarray): The data of the matrix as a 2D numpy array.
    """

    def __new__(cls, data):
        # Convert input data into a numpy array and ensure it's 2D
        obj = np.asarray(data)
        if obj.ndim not in [1, 2]:
            raise ValueError("A matrix must be either a 1D or 2D array.")

        # Handle 1D array by reshaping it into a 1xN matrix
        if obj.ndim == 1:
            obj = obj.reshape(1, -1)

        # Handle single-column matrix to row vector conversion
        if obj.ndim == 2 and obj.shape[1] == 1:
            obj = obj.T

        return obj.view(cls)

    def __repr__(self):
        return super().__repr__()

    def rank(self):
        return np.linalg.matrix_rank(self)

In [3]:
_a = [1, 2, 3]
_b = [11, 22, 33]
_c = [111, 222, 333]
_d = [111, 222, 333, 444]
_e = [1, 5, 19]
a, b, c, d, e = Vector(_a), Vector(_b), Vector(_c), Vector(_d), Vector(_e)

In [ ]:
 # Create an instance of Vector A
A = Vector([1, 2, 3])

# Simple tests for .find_span method
span_result_1 = A.find_span([1, 0, 0], [0, 1, 0], [0, 0, 1])
span_result_2 = A.find_span([1, 2, 3], [2, 4, 6])
span_result_3 = A.find_span([1, 2, 3], [4, 5, 6])
span_result_4 = A.find_span( [4, 5, 6], include_self=True)

print("Span Result 1:", span_result_1)
print("Span Result 2:", span_result_2)
print("Span Result 3:", span_result_3)
print("Span Result 4:", span_result_4)

In [ ]:
print(a.find_linear_combination(b, c))

In [ ]:
0.0008841  * b + 0.0089214 * c

In [ ]:
a.add_vector(b)

In [ ]:
a.scalar_multiply(21)

In [ ]:
a.is_dependent(d)

In [ ]:
a.is_linear_combination(d)

In [1]:
import numpy as np

In [2]:
class Matrix(np.ndarray):
    """
    A class representing a mathematical matrix that inherits from numpy.ndarray.

    This ensures that the Matrix behaves like a numpy array and supports all
    operations such as addition, multiplication, etc.

    Attributes:
        data (numpy.ndarray): The data of the matrix as a 2D numpy array.
    """

    def __new__(cls, *data, make_from_vectors=False):
        # Case when creating from vectors
        if make_from_vectors:
            # Ensure multiple vectors are passed
            if len(data) < 2:
                raise ValueError("At least two vectors are required to form a matrix.")
            vectors = [Vector(v) if not isinstance(v, Vector) else v for v in data]
            obj = np.column_stack(vectors)
        else:
            # Case when creating from a single matrix
            if len(data) != 1:
                raise ValueError("Only one argument is allowed when creating a matrix. To create a matrix from vectors, use `make_from_vectors=True`.")
            obj = np.asarray(data[0])

            if obj.ndim != 2:
                raise ValueError(f"A matrix must be a 2D array, got {obj.ndim}D.")

        return obj.view(cls)

    def rank(self):
        base_matrix = self
        return np.linalg.matrix_rank(base_matrix)

    def is_square(self):
        base_matrix = self
        return base_matrix.shape[0] == base_matrix.shape[1]
    
    # add shape validation and type checking Vector()
    def apply_on_vector(self, vector):
        base_matrix = self
        return base_matrix @ vector

    def inverse_matrix(matrix):
        matrix = Matrix(matrix) if not isinstance(matrix, Matrix) else matrix
        if matrix.shape[0] != matrix.shape[1]:
            raise ValueError("Only square matrices can be inverted.")
        return np.linalg.inv(matrix)

In [ ]:
def is_linear_transformation(transformation_matrix) -> bool:
    A = transformation_matrix
    validate_input(A)
    
    if not isinstance(A, Matrix):
        A = Matrix(A)
    n_vectors = A.shape[1]
    
    np.random.seed(42)  # Sets the seed
    # the number of rows of each vector should be equal to the number of cols of matrix (n vectors)
    v1 = Vector(np.random.random(size=(n_vectors,)))
    v2 = Vector(np.random.random(size=(n_vectors,)))
    c = np.random.rand()

    additivity = np.allclose(A @ v1 + A @ v2, A @ (v1 + v2))
    homogeneity = np.allclose(A @ (c * v1), c * (A @ v1))
    return additivity and homogeneity


m = [[1, 0], [0, 1]]
is_linear_transformation(m)

In [12]:
import numpy as np
from BaseTools import Vector, Matrix, validate_input, validate_equal_shapes, validate_multiplication_compatibility, validate_types

In [13]:
def apply_transformation(transformation_matrix, vector):
    
    A = transformation_matrix
    validate_input(A, vector)
    
    if not isinstance(A, Matrix):
        A = Matrix(A)
    if not isinstance(vector, Vector):
        vector = Vector(vector)
        
    validate_multiplication_compatibility(A, vector)
    
        
    return A @ vector

v = [1, 2]
m = [[0, -1], [1, 0]]
result = apply_transformation(m, v)
print(f"Transformed Vector: {result}")

Transformed Vector: [-2  1]


In [14]:
def compose_transformations(vector, *matrices):
    validate_input(vector, *matrices)

    # validate types    
    if not isinstance(vector, Vector):
        vector = Vector(vector)
    matrices = [Matrix(m) if not isinstance(m, Matrix) else m for m in matrices]

    # validate compatibility between matrices and a vector
    for matrix in matrices:
        validate_multiplication_compatibility(matrix, vector, raise_exception=True)

    result = vector

    for matrix in matrices:
        result = matrix @ result

        print(result)

    return result



# Test: Rotate vector v first 90 degrees to the left and then 180 degrees to the right

v = [1, 2]

rotated_vector = compose_transformations(v, [[0, -1], [1, 0]], [[-1, 0], [0, -1]])

print(f"Rotated Vector: {rotated_vector}")

[-2  1]
[ 2 -1]
Rotated Vector: [ 2 -1]


In [15]:
def matrix_multiply(matrix1, matrix2):
    validate_input(matrix1, matrix2)
    matrix1 = Matrix(matrix1) if not isinstance(matrix1, Matrix) else matrix1
    matrix2 = Matrix(matrix2) if not isinstance(matrix2, Matrix) else matrix2
    validate_multiplication_compatibility(matrix1, matrix2)


    return matrix1 @ matrix2

# Test 1: Multiply two 2x2 matrices
m1 = [[1, 2], [3, 4]]
m2 = [[2, 0], [1, 2]]
result = matrix_multiply(m1, m2)
print(f"Test 1 - Result:\n{result}")

# Test 2: Multiply a 2x3 matrix with a 3x2 matrix
m3 = [[1, 2, 3], [4, 5, 6]]
m4 = [[7, 8], [9, 10], [11, 12]]
result = matrix_multiply(m3, m4)
print(f"Test 2 - Result:\n{result}")

Test 1 - Result:
[[ 4  4]
 [10  8]]
Test 2 - Result:
[[ 58  64]
 [139 154]]


In [16]:
def transpose(matrix):
    validate_input(matrix)
    matrix = Matrix(matrix) if not isinstance(matrix, Matrix) else matrix

    n_rows, n_cols = matrix.shape[:2]
    new_n_rows = n_cols
    new_n_cols = n_rows

    new_matrix = np.zeros((new_n_rows, new_n_cols))
    for idx in range(new_n_rows):
        # go through empty new matrix rows, and assign cols of the original matrix to them
        new_matrix[idx] = matrix[:, idx]

    return Matrix(new_matrix)


# Test 1: Transpose a 2x3 matrix
m1 = np.array([[1, 2, 3], [4, 5, 6]])
print("Original:\n", m1)
print("Transposed:\n", transpose(m1))

# Test 2: Transpose a 3x2 matrix
m2 = np.array([[1, 2], [3, 4], [5, 6]])
print("Original:\n", m2)
print("Transposed:\n", transpose(m2))

# Test 3: Transpose a 1x4 matrix
m3 = np.array([[1, 2, 3, 4]])
print("Original:\n", m3)
print("Transposed:\n", transpose(m3))

# Test 4: Transpose a 4x1 matrix
m4 = np.array([[1], [2], [3], [4]])
print("Original:\n", m4)
print("Transposed:\n", transpose(m4))

# Test 5: Transpose a square matrix 2x2
m5 = np.array([[1, 2], [3, 4]])
print("Original:\n", m5)
print("Transposed:\n", transpose(m5))

Original:
 [[1 2 3]
 [4 5 6]]
Transposed:
 [[1. 4.]
 [2. 5.]
 [3. 6.]]
Original:
 [[1 2]
 [3 4]
 [5 6]]
Transposed:
 [[1. 3. 5.]
 [2. 4. 6.]]
Original:
 [[1 2 3 4]]
Transposed:
 [[1.]
 [2.]
 [3.]
 [4.]]
Original:
 [[1]
 [2]
 [3]
 [4]]
Transposed:
 [[1. 2. 3. 4.]]
Original:
 [[1 2]
 [3 4]]
Transposed:
 [[1. 3.]
 [2. 4.]]


In [17]:
def calculate_inverse_matrix(matrix):
    validate_input(matrix)
    matrix = Matrix(matrix) if not isinstance(matrix, Matrix) else matrix

    if not matrix.is_square():
        raise ValueError("Only square matrices can be inverted.")
    
    try:
        inv_matrix = np.linalg.inv(matrix)
    except np.linalg.LinAlgError as e:
        raise ValueError("Matrix is singular and cannot be inverted.")

    return Matrix(inv_matrix)

In [18]:
# Create matrices using the Matrix class
matrix1 = Matrix([[1, 2], [3, 4]])
matrix2 = Matrix([[2, 0], [0, 2]])
matrix3 = Matrix([[4, 7], [2, 6]])

# Check the inverse_matrix function
inv_matrix1 = calculate_inverse_matrix(matrix1)
inv_matrix2 = calculate_inverse_matrix(matrix2)
inv_matrix3 = calculate_inverse_matrix(matrix3)

print("Matrix 1:\n", matrix1)
print("Inverse of Matrix 1:\n", inv_matrix1)

print("Matrix 2:\n", matrix2)
print("Inverse of Matrix 2:\n", inv_matrix2)

print("Matrix 3:\n", matrix3)
print("Inverse of Matrix 3:\n", inv_matrix3)

Matrix 1:
 [[1 2]
 [3 4]]
Inverse of Matrix 1:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Matrix 2:
 [[2 0]
 [0 2]]
Inverse of Matrix 2:
 [[0.5 0. ]
 [0.  0.5]]
Matrix 3:
 [[4 7]
 [2 6]]
Inverse of Matrix 3:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [19]:
# Singular matrix (determinant is zero)
singular_matrix = Matrix([[1, 2, 4], [2, 4,5]])

try:
    inv_singular_matrix = calculate_inverse_matrix(singular_matrix)
except ValueError as e:
    print(f"Exception: {e}")

Exception: Only square matrices can be inverted.


In [1]:
from BaseTools import Vector, Matrix, validate_input, validate_equal_shapes, validate_multiplication_compatibility, validate_types
import numpy as np

In [2]:
def calculate_determinant(matrix):
    validate_input(matrix)
    # Matrix class ensures ndim == 2
    matrix = Matrix(matrix) if not isinstance(matrix, Matrix) else matrix

    if not matrix.is_square():
        raise ValueError("Only square matrices have a determinant.")

    if matrix.shape == (1, 1):
        determinant = matrix[0, 0]
    elif matrix.shape == (2, 2):
        determinant = matrix[0,0] * matrix[1,1] - matrix[0,1] * matrix[1,0]
    elif matrix.shape == (3, 3):
        a, b, c = matrix[0]
        d, e, f = matrix[1]
        g, h, i = matrix[2]
        determinant = (a * e * i) + (b * f * g) + (c * d * h) - (c * e * g) - (b * d * i) -( a * f * h)
    else:
        determinant = np.linalg.det(matrix)
    return float(determinant)

def calculate_trace(matrix):
    validate_input(matrix)
    matrix = Matrix(matrix) if not isinstance(matrix, Matrix) else matrix

    if not matrix.is_square():
        raise ValueError("Only square matrices have a trace.")

    n_rows = matrix.shape[0]
    trace = sum(matrix[i, i] for i in range(n_rows))
    return trace.astype(np.float64)


In [3]:
def find_diagonal(matrix):
    validate_input(matrix)
    matrix = Matrix(matrix) if not isinstance(matrix, Matrix) else matrix

    if not matrix.is_square():
        raise ValueError("Only square matrices have a diagonal.")

    n_rows = matrix.shape[0]
    diagonal = [matrix[i, i] for i in range(n_rows)]
    return Vector(diagonal)

def find_anti_diagonal(matrix):
    validate_input(matrix)
    matrix = Matrix(matrix) if not isinstance(matrix, Matrix) else matrix

    if not matrix.is_square():
        raise ValueError("Only square matrices have an anti-diagonal.")

    n_rows = matrix.shape[0]
    anti_diagonal = [matrix[i, n_rows-1-i] for i in range(n_rows)]
    return Vector(anti_diagonal)

In [4]:

    # Create matrices using the Matrix class
matrix1 = Matrix([[1, 2], [3, 4]])
print("digonal", find_diagonal(matrix1))
print("antidiagonal", find_anti_diagonal(matrix1))
matrix2 = Matrix([[2, 0], [0, 2]])
matrix3 = Matrix([[4, 7, 2], [3, 6, 1], [2, 5, 1]])

# Check the determinant function
det_matrix1 = calculate_determinant(matrix1)
det_matrix2 = calculate_determinant(matrix2)
det_matrix3 = calculate_determinant(matrix3)

print("Matrix 1:\n", matrix1)
print("Determinant of Matrix 1:", det_matrix1)

print("Matrix 2:\n", matrix2)
print("Determinant of Matrix 2:", det_matrix2)

print("Matrix 3:\n", matrix3)
print("Determinant of Matrix 3:", det_matrix3)


digonal Vector(1, 4)
antidiagonal Vector(2, 3)
Matrix 1:
 [[1 2]
 [3 4]]
Determinant of Matrix 1: -2.0
Matrix 2:
 [[2 0]
 [0 2]]
Determinant of Matrix 2: 4.0
Matrix 3:
 [[4 7 2]
 [3 6 1]
 [2 5 1]]
Determinant of Matrix 3: 3.0


In [5]:
def calculate_column_space(matrix):
    validate_input(matrix)
    matrix = Matrix(matrix) if not isinstance(matrix, Matrix) else matrix

    rank = matrix.rank()
    column_space = matrix[:, :rank]
    return column_space

In [6]:
def calculate_row_space(matrix):
    validate_input(matrix)
    matrix = Matrix(matrix) if not isinstance(matrix, Matrix) else matrix

    matrix = matrix.get_transpose()
    col_space = calculate_column_space(matrix)
    return col_space

In [7]:
# example with calculating row space
matrix = Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_space = calculate_row_space(matrix)
col_space = calculate_column_space(matrix)
row_space, col_space

(Matrix([[1, 4],
         [2, 5],
         [3, 6]]),
 Matrix([[1, 2],
         [4, 5],
         [7, 8]]))

In [8]:
# test 1 - matrix from 1 to 9
test_m = [[0, 0, 1], [0, 1, 0], [1, 0, 0]]
test_m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
test_matrix = [
    [1, 2, 3],
    [2, 4, 6],
    [3, 6, 9]
]
test_matrix = [
    [1, 0, 1],
    [0, 1, 1],
    [1, 1, 2]
]
calculate_column_space(test_m)
calculate_column_space(test_matrix)

Matrix([[1, 0],
        [0, 1],
        [1, 1]])

In [16]:
def vector_dot(v1, v2):
    validate_input(v1, v2)
    v1 = Vector(v1) if not isinstance(v1, Vector) else v1
    v2 = Vector(v2) if not isinstance(v2, Vector) else v2

    # the dot product of two vectors requires the same shape, in contrast to matrix multiplication,
    # which requires the number rows of the first matrix to be equal to the number of columns of the second matrix
    validate_equal_shapes(v1, v2)
    
    # the dot product of 2 vectors is element-wise multiplication followed by summation
    result = np.sum(v1 * v2)
    return float(result)

# Test 1: Dot product of two 1D vectors
v1 = [1, 2, 3]
v2 = [4, 5, 6]
result = vector_dot(v1, v2)
result
# print(result)

32.0

In [13]:
def matrix_vector_dot(matrix, vector):
    validate_input(matrix, vector)
    matrix = Matrix(matrix) if not isinstance(matrix, Matrix) else matrix
    vector = Vector(vector) if not isinstance(vector, Vector) else vector

    validate_multiplication_compatibility(matrix, vector)

    n_components = len(vector)
    result = Vector(
        np.zeros(
            n_components,
        )
    )

    for i in range(n_components):
        # each component of vector multiplied by corresponding columnn of the matrix
        result += vector[i] * matrix[:, i]
    return result


# Test 1: Dot product of a matrix and a vector
m1 = [[1, 2], [3, 4]]
v1 = [5, 6]
result = matrix_vector_dot(m1, v1)
print(result)

Vector(17.0, 39.0)


In [19]:
def matrix_dot(matrix1, matrix2):
    """
    Here is the logic of matrix multiplication from scratch:

    1. We consider the first matrix as the transformation matrix
    2. We consider the second matrix as the set of vectors (each column - 1 vector)
    3. If we apply 1st matrix (transformation matrix) to each column (vector) of the second matrix, we get corresponding transformed columns (vectors) for the resulting matrix.
    4. So it feels  like applying transformation on each vector and filling the resulting matrix with the transformed vectors.

    """
    validate_input(matrix1, matrix2)
    matrix1 = Matrix(matrix1) if not isinstance(matrix1, Matrix) else matrix1
    matrix2 = Matrix(matrix2) if not isinstance(matrix2, Matrix) else matrix2

    validate_multiplication_compatibility(matrix1, matrix2)

    # shape of resulting matrix
    n_rows = matrix1.shape[0]
    n_cols = matrix2.shape[1]
    result = Matrix(np.zeros((n_rows, n_cols)))

    # iterate over columns (vectors) of the 2nd matrix:
    for idx, vector in enumerate(matrix2):
        transformed_vector = matrix_vector_dot(matrix1, vector)
        result[:, idx] = transformed_vector
        # each column of resulting matrix is the transformed vector of the corresponding column of the 2nd matrix
        print(vector, transformed_vector)

    return result


# Test 1: Multiply two 2x2 matrices
m1 = [[1, 2], [4, 3]]
m2 = [[3, 4], [4, 8]]
result = matrix_dot(m1, m2)
result

[3 4] Vector(11.0, 24.0)
[4 8] Vector(20.0, 40.0)


Matrix([[11., 20.],
        [24., 40.]])